### PR TITLE
simplify and coding style

### PR DESCRIPTION
**Pull request by fabianfrz**
Give it a try and merge if it still works (have not tested it)

Changes:

* convert tabs to spaces
* deduplicate event handler object

### CODE REVIEW

**Comment by marjohn56** [comment]
Works very nicely.

**Comment by opnsenseuser** [comment]
@fabianfrz Thats Great. Tipps from a pro are welcome. Thx Fabian. I have to learn a lot but i Love it.....thx 
@marjohn56 you also Need some fixes on your Template. Like font-size, padding.... See my Plugin prˋs i have done. I also did a modification for the original theme. See my prs....thx Martin for testing

**Comment by opnsenseuser** [comment]
@fabianfrz  your improvements work without any problems. Do i have to make a new pr for your modification? I will now compare both files to see what i can do better next time. 
I really thank you. That's great. 

best regards rené

**Comment by opnsenseuser** [comment]
@fabianfrz ok, sorry...now i See. I automatically merged this. Ok

**Comment by fabianfrz** [comment]
@opnsenseuser the merged file should go into your merge request so it should be visible in the other repository. You should know that a branch is just a tag for a series of commits. You can always commit on it so you don't have to create a new pull request etc. The diff just updates.

**Pull request merged**
